apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.deploymentName }}-gateway
  namespace: {{ .Values.gateWayNamespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ .Values.hostName }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.certmanager.secretName }}
