apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.deploymentName }}-gateway
  namespace: {{ .Values.gateWayNamespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    {{- if .Values.certmanager.enabled }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
      {{- range .Values.hosts }}
        - {{ . }}
      {{- end }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.certmanager.secretName }}
    {{- end }}
