apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.deploymentName }}-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  {{- range .Values.hosts }}
    - {{ . }}
  {{- end }}
  exportTo:
  - "."
  - istio-ingress
  - istio-system
  gateways:
    - {{ .Values.gateWayNamespace }}/{{ .Values.deploymentName }}-gateway
    - mesh
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Values.deploymentName }}-service.{{ .Values.namespace }}.svc.cluster.local
            port:
              number: {{ .Values.service.port }}